### ISSUE TITLE
当使用compileSdkVersion 27时程序崩溃

### ISSUE THREAD

**Issue by mudcastles** [yaozs/ImageShowPicker#14]
我使用compileSdkVersion 27，targetSdkVersion 27，implementation 'com.android.support:appcompat-v7:27.1.1'并且implementation 'com.android.support:recyclerview-v7:27.1.1'，运行时会崩溃。Log如下：
`
02-03 15:29:31.726 14411-14411/com.peng.administrator.qhdkeyperson E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.peng.administrator.qhdkeyperson, PID: 14411
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.v7.widget.RecyclerView$ViewHolder.shouldIgnore()' on a null object reference
        at android.support.v7.widget.RecyclerView.findMinMaxChildLayoutPositions(RecyclerView.java:3989)
        at android.support.v7.widget.RecyclerView.didChildRangeChange(RecyclerView.java:4005)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3908)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3540)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
        at android.view.View.layout(View.java:16952)
        at android.view.ViewGroup.layout(ViewGroup.java:5580)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
        at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1990)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1755)
        at android.view.View.layout(View.java:16952)
        at android.view.ViewGroup.layout(ViewGroup.java:5580)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
        at android.view.View.layout(View.java:16952)
        at android.view.ViewGroup.layout(ViewGroup.java:5580)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
        at android.view.View.layout(View.java:16952)
        at android.view.ViewGroup.layout(ViewGroup.java:5580)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
        at android.view.View.layout(View.java:16952)
        at android.view.ViewGroup.layout(ViewGroup.java:5580)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
        at android.support.v4.widget.NestedScrollView.onLayout(NestedScrollView.java:1674)
        at android.view.View.layout(View.java:16952)
        at android.view.ViewGroup.layout(ViewGroup.java:5580)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1189)
        at android.view.View.layout(View.java:16952)
        at android.view.ViewGroup.layout(ViewGroup.java:5580)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
        at android.view.View.layout(View.java:16952)
        at android.view.ViewGroup.layout(ViewGroup.java:5580)
        at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:443)
        at android.view.View.layout(View.java:16952)
        at android.view.ViewGroup.layout(ViewGroup.java:5580)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
        at android.view.View.layout(View.java:16952)
        at android.view.ViewGroup.layout(ViewGroup.java:5580)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
        at android.view.View.layout(View.java:16952)
        at android.view.ViewGroup.layout(ViewGroup.java:5580)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
        at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2807)
        at android.view.View.layout(View.java:16952)
        at android.view.ViewGroup.layout(ViewGroup.java:5580)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2547)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2250)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1321)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6763)
    	at

`

**Comment by yaozs** [comment]
@Gaoxinp 现最新版本已修复
