### ISSUE TITLE
有一个问题。

### ISSUE THREAD

**Issue by memedahui** [yaozs/ImageShowPicker#2]
当item图片过多（超过一屏）后，向下滑动就会报错！
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.project.administrator, PID: 6961
                  java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true
                      at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:5736)
                      at android.support.v7.widget.RecyclerView$Recycler.recycleView(RecyclerView.java:5680)
                      at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:289)
                      at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:336)
                      at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:349)
                      at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:356)
                      at android.support.v7.widget.GapWorker.run(GapWorker.java:387)
                      at android.os.Handler.handleCallback(Handler.java:815)
                      at android.os.Handler.dispatchMessage(Handler.java:104)
                      at android.os.Looper.loop(Looper.java:192)
                      at android.app.ActivityThread.main(ActivityThread.java:5886)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1031)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)

**Comment by yaozs** [comment]
谢谢反馈，我找一下问题

**Comment by yaozs** [comment]
请问你是怎么使用的，我在demo中加载超过1屏之后，没有发现该问题，有什么特殊操作吗

**Comment by yaozs** [comment]
这个问题我找到了，正在尝试修复，好的话我会在这里通知你

**Comment by LiuJiaWen123** [comment]
你好，那个ImageShowPickerView会存在缓存的问题，就是我这次在第一个+里面选择了一个图片，然后退出来Activity，再进来这个Activity来选择第一个+的时候，显示的不是我当前选到的图片，而是上一次的，求解

**Comment by LiuJiaWen123** [comment]
求解答[捂脸]

**Comment by yaozs** [comment]
@LiuJiaWen123 demo更新，使用问题，非框架问题

**Comment by junge89221** [comment]
请问这个问题解决了吗？我下载的最新的demo也出现这个问题，上滑的时候 报错，报错信息同上~~求解决！

**Comment by yaozs** [comment]
@junge89221 demo，已更新

**Comment by junge89221** [comment]
没有看到更新哦··问题出现在one_picker 那个demo，列表上是没有问题的，如果在one_picker外层套一个scrollView就没有问题！

**Comment by yaozs** [comment]
这回再看看，刚才忘提交了，one_picker有什么问题呢，你先更新下看看
