### ISSUE TITLE
2个问题1个建议

### ISSUE THREAD

**Issue by FlogFly** [yaozs/ImageShowPicker#6]
问题1：那个自带的Demo，选List_picker ,当一直往下划，直接报错
  Process: com.yzs.imageshowpicker, PID: 19303
                                                                         java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true
                                                                             at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:5736)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.recycleView(RecyclerView.java:5680)
                                                                             at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:289)
                                                                             at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:336)
                                                                             at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:349)
                                                                             at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:356)
                                                                             at android.support.v7.widget.GapWorker.run(GapWorker.java:387)
                                                                             at android.os.Handler.handleCallback(Handler.java:739)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5458)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

问题2： 我看你的onePicker选择是当选了九张后，那个添加图片的加号就没有了。你的每次去图库选也的确是做了限制，最多选9张。但是你这边有个bug。就是我先去图库选3张，我再点击进入图库选8张。然后确定出来。上面有11张图片。。加号也没有了。然后我要删图片，删到小于9张，才出来加号。。所以我第一次加8张，第二次加9张，其实我最多加了17张。应该在图库选图片的时候把已经加入的数量也要统计进去

建议3：
最好添加好后。点击图片后能够放大查看。然后可以再放大的界面有个删除，像微信一样。

**Comment by yaozs** [comment]
回答这几个问题
第一个确实有问题，目前正在研究，这个问题出线在单个item超出1屏时出线，正常情况下，是不会超过一屏的
第二个问题，那个是demo写的问题，一会会改下demo，
建议：这个我考虑过，但是由于有的需求没有这个放大的要求，点击会出线其他操作，所以我只提供了点击事件，具体怎么操作由用户决定，不过也可以考虑添加进默认点击，我再考虑一下，如果添加的话，怎么个逻辑
