### ISSUE TITLE
选择图片时，如果图片过大，就会出现OOM

### ISSUE THREAD

**Issue by ningyibo** [yaozs/ImageShowPicker#9]
我在选择图片上传时，选择了几个比较大的图片，直接crash了。
 Process: com.zhongyinginfo.landa.doctor, PID: 896
                                                                            java.lang.OutOfMemoryError: Failed to allocate a 38937612 byte allocation with 16777120 free bytes and 27MB until OOM
                                                                                at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                                at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
                                                                                at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:635)
                                                                                at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:611)
                                                                                at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:391)
                                                                                at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:417)
                                                                                at android.graphics.drawable.Drawable.createFromPath(Drawable.java:1143)
                                                                                at android.widget.ImageView.resolveUri(ImageView.java:795)
                                                                                at android.widget.ImageView.setImageURI(ImageView.java:442)
                                                                                at com.zhongyinginfo.landa.doctor.utils.imageshowpickerview.Loader.displayImage(Loader.java:20)
                                                                                at com.zhongyinginfo.landa.doctor.utils.imageshowpickerview.Loader.displayImage(Loader.java:15)
                                                                                at com.zhongyinginfo.landa.doctor.utils.imageshowpickerview.ImageShowPickerAdapter.onBindViewHolder(ImageShowPickerAdapter.java:89)
                                                                                at com.zhongyinginfo.landa.doctor.utils.imageshowpickerview.ImageShowPickerAdapter.onBindViewHolder(ImageShowPickerAdapter.java:22)
                                                                                at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
                                                                                at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
                                                                                at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
                                                                                at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
                                                                                at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                                at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                                at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                                at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                                                                at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                                at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                                at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                                at com.zhongyinginfo.landa.doctor.utils.imageshowpickerview.MyGridLayoutManager.onLayoutChildren(MyGridLayoutManager.java:40)
                                                                                at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                                at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3025)
                                                                                at android.view.View.measure(View.java:17565)
                                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
                                                                                at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                                at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1083)
                                                                                at android.widget.LinearLayout.onMeasure(LinearLayout.java:615)
                                                                                at android.view.View.measure(View.java:17565)
                                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
                                                                                at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                                at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                                at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                                at android.view.View.measure(View.java:17565)
                                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
                                                                                at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                                at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                                at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                                at android.view.View.measure(View.java:17565)
                                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
                                                                                at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                                                at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                                at android.view.View.measure(View.java:17565)
                                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
                                                                            	at android.support.v7.widget.ActionBarOverlayLa

**Comment by yaozs** [comment]
这个和这个控件无关，和选择的图片加载框架有关

**Comment by ningyibo** [comment]
ok，找到原因了，谢谢
